config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[new create]
  resources :posts
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern

  before_action :require_login, except: [:new, :create]

  private

  def not_authenticated
    flash[:alert] = "You need to log in to access this page."
    redirect_to login_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new index create]

  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new, alert: 'There was an error creating the post.'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# Controller to login/logout users
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password])
    if user
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
# User controller to create new users
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: "Welcome, #{@user.email}!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Graphql Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" crossorigin="anonymous">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.slim
.container.mt-4
  h1.text-center.mb-4 All Posts

  = link_to 'New Post', new_post_path, class: "btn btn-success mb-4"

  - @posts.each do |post|
    .card.mb-3
      .card-body
        h2.card-title
          = link_to post.title, post_path(post), class: "text-decoration-none"
        h6.card-subtitle.mb-2.text-muted By #{post.user.email}
        p.card-text = truncate(post.body, length: 100)
        = link_to 'Read more', post_path(post), class: "btn btn-primary btn-sm"

app/views/posts/new.html.slim
.container.mt-5
  h1.text-center.mb-4 Create a New Post

  = form_with model: @post, local: true, class: "needs-validation" do |f|
    .mb-3
      = f.label :title, "Post Title", class: "form-label"
      = f.text_field :title, class: "form-control", placeholder: "Enter the post title", required: true

    .mb-3
      = f.label :body, "Post Body", class: "form-label"
      = f.text_area :body, class: "form-control", rows: 5, placeholder: "Write your post here...", required: true

    .d-grid.gap-2.mt-4
      = f.submit "Create Post", class: "btn btn-primary btn-block"

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :div, message.html_safe, class: "alert alert-#{key} alert-dismissible fade show", role: "alert" do
    = message
    button.close type="button" data-bs-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times;

app/views/shared/_navbar.html.slim
.navbar.navbar-expand-lg.navbar-light.bg-primary
  .container
    .d-flex.justify-content-between.align-items-center
      - if current_user
        .user-info
          p.text-white= current_user.email
      - else
        .nav-links
          = link_to 'Sign in', new_session_path, class: 'btn btn-outline-light'
          = link_to 'Sign up', new_user_path, class: 'btn btn-outline-light'
    .d-flex.ms-auto
      - if current_user
        .nav-links
          = link_to 'Sign out', logout_path, method: :delete, class: 'btn btn-outline-light'
        .nav-links
          = link_to ' | Main', root_path, class: 'btn btn-outline-light'

app/views/users/new.html.slim
h1.text-center.mb-4.mt-5 Register

.container
  .row.justify-content-center
    .col-md-6
      = form_with model: @user, class: "needs-validation", novalidate: true do |f|
        .mb-3
          = f.label :email, class: "form-label"
          = f.email_field :email, class: "form-control", placeholder: "Enter your email"
        .mb-3
          = f.label :password, class: "form-label"
          = f.password_field :password, class: "form-control", placeholder: "Enter your password"
        .mb-3
          = f.label :password_confirmation, class: "form-label"
          = f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm your password"
        .d-grid.gap-2
          = f.submit "Register", class: "btn btn-primary btn-block"